### PR TITLE
Github action for healthchecks

### PR DESCRIPTION
**Pull request by pallost**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tools/2)

### CODE REVIEW

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tools/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jschummer, @lassemaatta, @pallost, and @tk-vincit)

___
*[.github/workflows/test-healthcheck-action.yml, line 18 at r3](https://reviewable.io/reviews/hsldevcom/jore4-tools/2#-McxRGjREPGCzlRM8R1W:-McxRGjREPGCzlRM8R1X:b-hxqtgd) ([raw file](https://github.com/hsldevcom/jore4-tools/blob/fb3bf23a350f32697edefe64b80982bae10a06f3/.github/workflows/test-healthcheck-action.yml#L18)):*
> ```YAML
> 
>       - name: Verify that healthcheck succeeds
>         uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
> ```

You are using the action from 'healthcheck-v1' branch, should we create a separate branch for all actions that we add to the tools repository?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tools/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jschummer, @lassemaatta, @tk-vincit, @v1, and @v2)

___
*[.github/workflows/test-healthcheck-action.yml, line 18 at r3](https://reviewable.io/reviews/hsldevcom/jore4-tools/2#-McxRGjREPGCzlRM8R1W:-McxUDPpA5V9Yr2jEG87:bp6rz6o) ([raw file](https://github.com/hsldevcom/jore4-tools/blob/fb3bf23a350f32697edefe64b80982bae10a06f3/.github/workflows/test-healthcheck-action.yml#L18)):*
<details><summary><i>Previously, jpeuralinna (Joonas Peuralinna) wrote…</i></summary><blockquote>

You are using the action from 'healthcheck-v1' branch, should we create a separate branch for all actions that we add to the tools repository?
</blockquote></details>

Yes as we want to version each action separately. If we had global @v1, @v2 branches, we couldn't keep the git history straight but would need to do no-ff merges, which I prefer not to do

**Review by jpeuralinna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tools/2)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @jschummer, @lassemaatta, @tk-vincit, @v1, and @v2)

___
*[.github/workflows/test-healthcheck-action.yml, line 18 at r3](https://reviewable.io/reviews/hsldevcom/jore4-tools/2#-McxRGjREPGCzlRM8R1W:-McxV8hvAG9PPHYEZ-yj:b-b9kfhf) ([raw file](https://github.com/hsldevcom/jore4-tools/blob/fb3bf23a350f32697edefe64b80982bae10a06f3/.github/workflows/test-healthcheck-action.yml#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Yes as we want to version each action separately. If we had global @v1, @v2 branches, we couldn't keep the git history straight but would need to do no-ff merges, which I prefer not to do
</blockquote></details>

Okay, sounds smart. We should probably move other actions (like e2e-tests) to this repository too.

**Review by jpeuralinna — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 1 of 2 files at r2, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-tools/2)* status: all files reviewed, 1 unresolved discussion (waiting on @jschummer, @lassemaatta, @tk-vincit, @v1, and @v2)

**Pull request merged**
